### ISSUE TITLE
error occurred when testing the function 'fit' 

### ISSUE THREAD

**Issue by PuziJiang** [eprifti/predomics#1]
Dear sir,

I followed the vignette and tested the functions of predomics using the training data 'cir_train'. When I tried to fit a cross-validation model based on metal algorithm, there was an error as below. The version of R I used is 3.4.2. 

Could you help to resolve this question? Thanks very much!

Best regards,
Puzi

`
library(predomics)
library(doRNG)
library(gtools)
> X <- cir_train$X;
> y <- cir_train$y # set global variables
> X <- X[rowSums(X)!=0,];
> dim(X) # filter out variables with only zero values
[1] 556 181
> X <- filterNoSignal(X = X, side = 1, threshold = "auto", verbose = FALSE);
> dim(X)
[1] 462 181
> clf <- metal(nCores = 2,   seed = 1,  plot = FALSE )
> printy(clf) # print the object for more information
[1] "Summary of Classifier object"
========== Experiment ==========
	--- id: metal
	--- description: metal Tue Aug 18 16:48:01 2020
	--- save: nothing
========== Learner ==========
	--- learner: metal
	--- objective: auc
	--- sparsity: 1,2,3,4,5,6,7,8,9,10
	--- max.nb.features: 1000
	--- saveFiles: FALSE
	--- pathSave: NULL
	--- plot: FALSE
	--- verbose: TRUE
	--- warnings: FALSE
	--- debug: FALSE
	--- print_ind_method: short
	--- nCores: 2
	--- parallel: TRUE
	--- parallelize.folds: TRUE
	--- parallel.local: FALSE
	--- seed: 1
	--- testAllSigns: FALSE
	--- evalToFit: accuracy_
	--- k_penalty: 0
	--- language: mix
	--- popSaveFile: NULL
	--- epsilon: NULL
	--- scoreFormula: function
	--- intercept: NULL
	--- unificator.method: terga2
	--- unificator.evolver: v2m_new
	--- terBeam
	--- terda
	--- terga2
	--- terBeam
	--- terda
	--- terga2
	--- terBeam
	--- terga2
	--- terga2
> isClf(clf)  # test whether the object is a classifier
[1] TRUE
> class(clf)  # the class of the classifier object
[1] "list"
> res_clf <- fit(X = X,  y = y, clf = clf,   cross.validate = TRUE, nfolds = 10);
... Database X is not a matrix! Converting ...
... Classification mode, computing factor(y) for speedup and robustness
... Computing feature correlation for speedup
... ... filterfeaturesK: Executing Wilcoxon test
|********************************************************************************************|
... Storing data in the classifier object for speedup
... Computing ternary coefficients for speedup
... One seed found, setting by default
... Running the classifier metal in parallel mode with  3 CPUs
... Setting epsilon for predomics learners
... model fitting based on aggregating different Heuristics ...
... Cross validation mode
... All the  11  CV folds are set
... Starting CV in parallel
... Cross validation finished
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
[1] "Error in combinations(n = length(ind.features.to.keep), r = sparsity,  : \n  could not find function \"combinations\"\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in combinations(n = length(ind.features.to.keep), r = sparsity,     v = ind.features.to.keep): could not find function "combinations">
... All results from cross validation are dispatched
Error: $ operator is invalid for atomic vectors`

**Comment by eprifti** [comment]
Hello,
It looks like the function combinations is not found. Please make sure the package gtools is installed. There is the following requirement in the package importFrom(gtools,combinations)
Best
Edi

**Comment by eprifti** [comment]
Did it work ?

**Comment by jdzucker** [comment]
Dit it work ?
best
